### ISSUE TITLE
두개의 canvas 를 띄웠을때 initConfig 충돌나는 문제점 발견

### ISSUE THREAD

**Issue by kimscott** [hrkenshin/OpenGraph#39]
한개의 캔버스 위쪽에 또다른 캔버스를 팝업으로 띄워서 작업을 할적에
두번째 팝업에서는 initConfig를 drag가 안되도록 설정이 되어있다면 
팝업창을 닫았을때에도 기존의 canvas 에 새롭게 도형을 올렸을경우
drag가 안되는 문제점 발견.

initConfig 가 섞여 버리는 걸까요?

**Comment by hrkenshin** [comment]
initConfig 할때 OG.Constants 에 설정을 해서 그런거 같네요. OG.Constants 는 각 캔버스에서 공유가되니...
교통정리좀 해주면 어렵지않게 처리될듯해요.

**Comment by kimscott** [comment]
canvas = new OG.Canvas('canvas2');
    canvas.initConfig({
        selectable      : true,
        dragSelectable  : false,
        movable         : false,
        resizable       : false,
        connectable     : true,
        connectCloneable: false,
        connectRequired : true,
        labelEditable   : false,
        groupDropable   : false,
        collapsible     : false,
        enableHotKey    : true
    });

이런식으로 했는데....
이건 OG.Constants 에 바로 적용을 한게 아닌것 같은데.. 
다른 방식으로 해줘야 하는걸까요?

**Comment by hrkenshin** [comment]
아뇨 설정은 제대로 하신게 맞고 단 initConfig 할때 내부적으로 OG.Constants 에 설정을 하게되서 그래요. 제쪽에서 리팩토링을 좀 해야겠어요. selectable, movable.. 이런 속성을 OG.Constants 에서 빼야될거 같아요. 미처 생각못한 부분이네요.

**Comment by hrkenshin** [comment]
근데 좀더 생각해보니 OG.Constants 에 있는 다른 부분도 문제가 되네요. style 관련된 부분도 있는데 이것도 캔버스별로 분리를 해야할듯. 음. 일이 커지네요 ㅠㅠ 대공사일듯...
필요한 기능이라 생각되니 todo 에 올려둘게요
