### ISSUE TITLE
canvas.onRemoveShape(function (event, shapeElement)  리스너가 정상작동 안함

### ISSUE THREAD

**Issue by kimscott** [hrkenshin/OpenGraph#40]
리무브 되었을때 
canvas.onRemoveShape(function (event, shapeElement) {
            console.log('onRemoveShape', shapeElement);
});
이런식으로 이벤트 리스너를 받을적에 shapeElement 가 무조건 null로 옵니다..

OG.renderer.RaphaelRenderer.prototype.removeShape : function 
의 트리거가 걸릴적에 1번: $(this._PAPER.canvas).trigger('removeShape', [rElement.node]);

이런식으로 걸리는데 다른부분은 
2 번 : $(this._PAPER.canvas).trigger('removeShape', [elememt]); 를 넘기던데..
이런식으로 쓰는게 맞는 걸까요?  

도형이 삭제될때, 연결되어있는 lineElemet 도 같이 삭제가 되는데
2번 방식으로 해봤을적에 LineElement 는 삭제가 될때 체크가 안되는듯 해요..

그럼 1번 방식이 맞다는 뜻 같기도 한데.. 지금 null 로 넘어오니.. 
도형을 삭제할때 해당 line 을 찾고싶은데 찾을수가 없습니다.

**Comment by hrkenshin** [comment]
onRemoveShape 은 삭제된 버린후니 해당 element 정보가 없어서 null 로 나오구요. onBeforeRemoveShape 을 이용하면 되요.
삭제된 후의 element 인스턴스는 복제를 해서 넘기는 방식으로 개선은 해야겠네요.
그리고, 연결된 line 이 같이 삭제될 때 removeShape 이벤트도 던져지도록 개선해야겠구요.
우선은 onBeforeRemoveShape 으로 삭제되는 element 얻어와서 연결된 line 을 찾으면 될거 같아요.

**Comment by hrkenshin** [comment]
참 코드 둘러보니, Shape 삭제될 때 연결된 line 도 같이 삭제될 때는 onDisconnectShape 을 이용하면 되요.
Shape 삭제될때 연결된 line 삭제될 때는 line 에 대해선 별도로 onRemoveShape 이벤트는 던지지 않을 생각입니다.
onRemoveShape 때 null 대신 복제된 인스턴스를 던지도록 할겁니다.
